# CircleCI configuration file
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - checkout
      - run: |
          cd /root/project/java
          mvn install -DskipTests -Dcheckstyle.skip -Drat.skip=true
          mkdir -p /root/project/artifacts
          mv /root/project/java/flight/flight-jdbc-driver/target/flight-jdbc-driver-*-SNAPSHOT.jar /root/project/artifacts/flight-jdbc-driver-sxt-${CIRCLE_SHA1:0:7}.jar
      - persist_to_workspace:
          root: /root
          paths:
            - project/
      - store_artifacts:
          path: /root/project/artifacts

  deploy:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - attach_workspace:
          at: /root
      - run: |
          mkdir -p /root/.m2
          echo '<settings><servers><server><id>${repo.id}</id><username>${repo.login}</username><password>${repo.pwd}</password></server></servers></settings>' > /root/.m2/settings.xml
          cd /root/project/java
          mvn deploy -DskipTests -Drat.skip=true -Dcheckstyle.skip -DaltDeploymentRepository="snapshots::default::$ARTIFACTORY_URL" -e -Drepo.id=snapshots -Drepo.login=$ARTIFACTORY_USER -Drepo.pwd="$ARTIFACTORY_API_KEY" -Dmaven.install.skip=true

workflows:
  maven_package:
    jobs:
      - build
      - deploy:
          requires: 
            - build
