# CircleCI configuration file
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - checkout
      - run: |
          cd $CIRCLE_WORKING_DIRECTORY/java
          mvn install -DskipTests -Dcheckstyle.skip -Drat.skip=true
          mkdir -p $CIRCLE_WORKING_DIRECTORY/artifacts
          mv $CIRCLE_WORKING_DIRECTORY/java/flight/flight-jdbc-driver/target/flight-jdbc-driver-*-SNAPSHOT.jar $CIRCLE_WORKING_DIRECTORY/artifacts/flight-jdbc-driver-sxt-${CIRCLE_SHA1:0:7}.jar
      - store_artifacts:
          path: $CIRCLE_WORKING_DIRECTORY/java/artifacts

workflows:
  maven_package:
    jobs:
      - build
