# CircleCI configuration file
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - checkout
      - run: |
          cd java
          mvn install -DskipTests -Dcheckstyle.skip -Drat.skip=true
          mkdir -p artifacts
          echo "list dir"
          ls -l java/flight/flight-jdbc-driver/target/
          echo "list file"
          ls -l java/flight/flight-jdbc-driver/target/flight-jdbc-driver-*-SNAPSHOT.jar
          mv java/flight/flight-jdbc-driver/target/flight-jdbc-driver-*-SNAPSHOT.jar artifacts/flight-jdbc-driver-sxt-${CIRCLE_SHA1:0:7}.jar
      - store_artifacts:
          path: java/artifacts

workflows:
  maven_package:
    jobs:
      - build
