# CircleCI configuration file
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  clean:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - run: ./mvnw clean
  build:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true -Dmaven.javadoc.skip=true package
      - persist_to_workspace:
          root: ./
          paths:
            - target/
  test:
    docker:
      - image: cimg/openjdk:11.0.13
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: ./mvnw test


workflows:
  maven_package:
    jobs:
      - clean
      - build:
          requires:
            - clean
      - test:
          requires:
            - build
