# CircleCI configuration file
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - checkout
      - run: cd java && mvn install -DskipTests -Dcheckstyle.skip -Drat.skip=true
      - store_artifacts:
          path: java/flight/flight-jdbc-driver/target/flight-jdbc-driver-*-SNAPSHOT.jar
      - persist_to_workspace:
          root: ./java
          paths:
            - target/
  test:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - checkout
      - attach_workspace:
          at: ./java/target
      - run: cd java && mvn test

workflows:
  maven_package:
    jobs:
      - build
      - test:
          requires:
            - build
