# CircleCI configuration file
version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    docker:
      - image: maven:3.8.6-jdk-8
    steps:
      - checkout
      - run: cd java && mvn install -DskipTests -Dcheckstyle.skip -Drat.skip=true
      - store_artifacts:
          path: java/flight/flight-jdbc-driver/target/

workflows:
  maven_package:
    jobs:
      - build
